# Introduction to NumPy

[NumPy: Baisc Array Operations](#NumPy:-Baisc-Array-Operations)

[Array Attributes and Methods](#Array-Attributes-and-Methods)
 -  [YouTube | CodeBasics](https://www.youtube.com/watch?v=a8aDcLk4vRc)
 
[Basic Math Operations](#Basic-Math-Operations)

[LMS Examples & Practices](#LMS-Examples-&-Practices)

## Intro

In [2]:
import numpy as np
import time
import sys

In [3]:
np.__version__

'1.23.1'

In [4]:
num_range = range(1000)

In [5]:
print(num_range)

range(0, 1000)


In [6]:
print(sys.getsizeof(5)*len(num_range))

28000


In [7]:
array = np.arange(1000)
print(array.size*array.itemsize)

4000


In [8]:
size = 1000000

In [9]:
l1 = range(size)
l2 = range(size)

In [10]:
a1 = np.arange(size)
a2 = np.arange(size)

In [11]:
# Python list
start = time.time()
result = [(x+y) for x, y in zip(l1,l2)]
print("python list took: ",(time.time()-start)*1000);

python list took:  99.01881217956543


In [12]:
# Numpy array
start = time.time()
result = a1+a2
print("numpy took: ",(time.time()-start)*1000);

numpy took:  18.609285354614258


## NumPy: Baisc Array Operations

Creating NumPy arrays from a list,  
Creating NumPy arrays using built-in methods such as:

In [13]:
import numpy as np
import time
import sys

### ```.arange```
Returns an ndarray object containing evenly spaced values within a given range

In [14]:
np.arange(0,20,4)

array([ 0,  4,  8, 12, 16])

In [15]:
# To print an output
print(np.arange(0,20,4))

[ 0  4  8 12 16]


### ```.linspace```
Returns the number of evenly spaced values between the interval is specified

In [70]:
# equal pieces
np.linspace(0,20,4)

array([ 0.        ,  6.66666667, 13.33333333, 20.        ])

### ```.random```
Return random floats in the half-open interval [0.0, 1.0).

In [17]:
np.random.seed(101) # te get the same results every time
np.random.rand(3)

array([0.51639863, 0.57066759, 0.02847423])

### ```.zeros```
Returns a new array of specified size, filled with zero

In [18]:
np.zeros(6,dtype=int)

array([0, 0, 0, 0, 0, 0])

### ```.ones```
Returns a new array of specified size and type, filled with ones


In [19]:
np.ones(4)

array([1., 1., 1., 1.])

### Array Attributes and Methods
[YouTube | CodeBasics](https://www.youtube.com/watch?v=a8aDcLk4vRc)

### ```.shape```
the shape tuple give the lengths of the corresponding array dimensions

In [79]:
arr = np.arange(8)
arr.shape

(8,)

In [93]:
a_1 = np.array([[1,2],[3,4],[5,6]])
a_1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [96]:
a_1.shape

(3, 2)

### ```.reshape```
Gives a new shape to an array without changing its data.

In [107]:
arr.reshape(8,1).shape
arr;
print(arr)

[0 1 2 3 4 5 6 7]


In [108]:
a_1.reshape(2,3)
a_1;
print(a_1)

[[1 2]
 [3 4]
 [5 6]]


In [109]:
a_1.reshape(6,1)
a_1;
print(a_1)

[[1 2]
 [3 4]
 [5 6]]


### ```.ravel```


In [84]:
arr.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [110]:
a_1.ravel()

array([1, 2, 3, 4, 5, 6])

In [111]:
a_1

array([[1, 2],
       [3, 4],
       [5, 6]])

### ```.max```
Return the maximum along a given axis.

In [22]:
np.random.seed(101)
ranarr = np.random.randint(0,50,10)
ranarr

array([31, 11, 17,  6, 23, 11, 47,  9, 13, 40])

In [23]:
ranarr.max()

47

### ```.min```
Return the minimum along a given axis.

In [24]:
ranarr.min()

6

### ```.sum```

In [112]:
a_1.sum()

21

In [113]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [114]:
a_1.sum(axis=0)

array([ 9, 12])

In [115]:
a_1.sum(axis=1)

array([ 3,  7, 11])

### ```.sqrt```

In [116]:
np.sqrt(a_1)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

### ```.std```

In [117]:
np.std(a_1)

1.707825127659933

### ```.argmax```
Return the index of the maximum element along a given axis

In [25]:
ranarr.argmax()

6

### ```.argmin```
Return the index of the minimum element along a given axis

In [26]:
ranarr.argmin()

3

## Basic Math Operations

In [126]:
array_a = np.array([[1,2], [3,4]])
array_a

array([[1, 2],
       [3, 4]])

In [127]:
array_b = np.array([[5,6], [7,8]])
array_b

array([[5, 6],
       [7, 8]])

In [128]:
array_a+array_b

array([[ 6,  8],
       [10, 12]])

In [129]:
array_a*array_b

array([[ 5, 12],
       [21, 32]])

In [132]:
array_a.dot(array_b)
# To do a matrix product!!

array([[19, 22],
       [43, 50]])

## LMS Examples & Practices

In [27]:
print(np.arange(0,20,3))

[ 0  3  6  9 12 15 18]


In [28]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [29]:
np.linspace(0,40,5)

array([ 0., 10., 20., 30., 40.])

In [30]:
np.random.randint(1,10)

5

### ```.ndim```
the number of axes (dimensions) of the array.

In [35]:
np.random.seed(42)
array_1 = np.random.randint(10,size=10)
array_1

array([6, 3, 7, 4, 6, 9, 2, 6, 7, 4])

In [37]:
# rows and columns = 2 dimentions
array_1.ndim

1

### ```.shape```
The dimensions  of the array. This is a tuple of integers indicating the size of the array in each dimension. 

In [42]:
array_b = np.random.randint(10,size=(3,5))
array_b

array([[3, 1, 5, 5, 9],
       [3, 5, 1, 9, 1],
       [9, 3, 7, 6, 8]])

In [41]:
array_b.shape

(3, 5)

### ```.size```
The total number of elements of the array. This is equal to the product of the elements of shape.

In [43]:
array_b.size

15

### ```.dtype```
An object describing the type of the elements in the array.

In [45]:
array_b.dtype

dtype('int32')

### ```.itemsize```
The size in bytes of each element of the array. It is equivalent to  ```.dtype.itemsize```.

In [46]:
array_b.itemsize

4

### ```.concatenate```
The size in bytes of each element of the array. It is equivalent to  ```.dtype.itemsize```.

In [49]:
x_a = np.array([1,2,3])
x_b = np.array([4,5,6])

In [50]:
np.concatenate([x_a,x_b])

array([1, 2, 3, 4, 5, 6])

### ```.split```
Splits an array into multiple sub-arrays as views into array.

In [53]:
x_c = np.array([1,2,3,55,66,88,94,65,3,2,1])
x_c

array([ 1,  2,  3, 55, 66, 88, 94, 65,  3,  2,  1])

In [61]:
np.split(x_c,[3,5])

[array([1, 2, 3]), array([55, 66]), array([88, 94, 65,  3,  2,  1])]

### ```.sort```
Return a sorted copy of an array.

In [63]:
v1 = np.array([2,1,4,3,5])
v1

array([2, 1, 4, 3, 5])

In [64]:
np.sort(v1)

array([1, 2, 3, 4, 5])

In [67]:
v1.sort() # Sorted in place

In [69]:
v1

array([1, 2, 3, 4, 5])