# NumPy: Indexing and Selection Operations

[Indexing and Slicing](#ndexing-and-Slicing)

   -  [YouTube | CodeBasics](https://www.youtube.com/watch?v=_d_Ka-ks2a0)


[Indexing with boolean array](#Indexing-with-boolean-array)

[LMS Examples & Practices](#LMS-Examples-&-Practices)


## Indexing and Slicing

In [1]:
import numpy as np

In [2]:
np.__version__

'1.23.1'

In [4]:
n = [6,7,8]
n[0:1]

[6]

In [5]:
n[0:2]

[6, 7]

In [6]:
n[-1]

8

In [7]:
a=np.array([6,7,8])

In [8]:
a[0:2]

array([6, 7])

In [9]:
a[-1]

8

In [10]:
ab=np.array([[6,7,8],[1,2,3],[9,3,2]])

In [11]:
ab

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [14]:
ab[1,2]

3

In [15]:
ab[0:2,2]

array([8, 3])

In [16]:
ab[-1]

array([9, 3, 2])

In [17]:
ab[-1,0:2]

array([9, 3])

In [18]:
ab[:,1:3]

array([[7, 8],
       [2, 3],
       [3, 2]])

In [19]:
ab

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [20]:
for row in ab:
    print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [21]:
for row in ab:
    print(row[1])

7
2
3


In [23]:
for cell in ab.flat:
    print(cell)

6
7
8
1
2
3
9
3
2


### ```.vstack```, ```.hstack```

In [27]:
aa=np.arange(6).reshape(3,2)
bb=np.arange(6,12).reshape(3,2)

In [28]:
aa

array([[0, 1],
       [2, 3],
       [4, 5]])

In [29]:
bb

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [32]:
np.vstack((aa,bb)) # Vertical

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [33]:
np.hstack((aa,bb)) # Horizontal

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

### ```.hsplit```, ```.vsplit```

In [51]:
cc=np.arange(30).reshape(2,15)
cc

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [52]:
np.hsplit(cc,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [53]:
result = np.hsplit(cc,3)

In [54]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [55]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [56]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [57]:
result = np.vsplit(cc,2)

In [58]:
result[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [59]:
result[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

### Indexing with boolean array

In [62]:
dd=np.arange(12).reshape(3,4)
dd

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [65]:
ee = dd > 4
ee

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [66]:
dd[ee]

array([ 5,  6,  7,  8,  9, 10, 11])

In [69]:
dd[ee]=-1 
# If we want to replace False boolean values with a certain number/values.

In [68]:
dd

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

## LMS Examples & Practices

In [71]:
import numpy as np
arr = np.arange(0,11)

In [73]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
arr[2:5]

array([2, 3, 4])

In [79]:
import numpy as np
arr = np.arange(1,8)
arr[arr>4]

array([5, 6, 7])

In [77]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [80]:
import numpy as np
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,50]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 50]])

In [82]:
arr_2d[0,2]

15